var express = require('express');
var router = express.Router();
const { getDirectory } = require('./secured/getDirectory');
const { userAuthentication } = require('./open-service/user-authentication');
const { createDirectory } = require('./secured/createDirectory');
const { removeItemPermanently } = require('./secured/removeItemPermanently');
const { renameItem } = require('./secured/renameItem');
const { shareItem } = require('./secured/shareItem');
const { removePermission } = require('./secured/removePermission');
const { moveItems } = require('./secured/moveItems');
const { createCopy } = require('./secured/createCopy');
const { uploadItem } = require('./secured/uploadItem');
const { moveToTrash } = require('./secured/moveToTrash');
const { emptyTrash } = require('./secured/emptyTrash');
const multer = require('multer');
const { restoreItems } = require('./secured/restoreItems');
const { getImage } = require('./secured/getImage');
const upload = multer();

router.get('/getDirectory',getDirectory ); // POSTA ÇEVİR
router.post('/userAuthentication', userAuthentication );
router.post('/uploadItem', upload.single('file'), uploadItem);
router.get('/createDirectory', createDirectory);
router.get('/removeItemPermanently', removeItemPermanently);
router.get('/renameItem', renameItem);
router.get('/shareItem', shareItem);
router.get('/removePermission', removePermission);
router.get('/moveItems',moveItems);
router.get('/createCopy',createCopy);
router.get('/moveToTrash', moveToTrash);
router.get('/emptyTrash',emptyTrash);
router.post('/restoreItems',restoreItems);
router.get('/getImage',getImage);
module.exports = router;
